server:
  port: ${PORT:8082}
  servlet:
    context-path: /notification
spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/db_notification_service?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: A1@@@b2c3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        ddl-auto: update
    show-sql: true 
    generate-ddl: true
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: awstreino@gmail.com
    password: awstreino@123
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
          quitwait: true
    test-connection: true
    
cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: AKIATVIWU7HDSYUXK26J
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/251839969735/sqsSendEmail